### ISSUE TITLE
MSET compressing keys instead of values

### ISSUE THREAD

**Issue by DinisEsteves** [b1rdex/predis-compressible#7]
When using the MSET, trying to compress the following array: 

`["foo" => "bar", "test" => "abc"]`

The output is the compressed keys instead of values.

This could be fixed, by changing the index in the for loop of the StringSetMultiple to 1 instead of 0;

**Comment by b1rdex** [comment]
Hi @DinisEsteves! If you have the time, would you be able to provide a PR to fix the issue?

**Comment by DinisEsteves** [comment]
> Hi @DinisEsteves! If you have the time, would you be able to provide a PR to fix the issue?

Done ;)

**Comment by b1rdex** [comment]
Thanks!
